name: Github Workflow Validator

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up asdf
        uses: asdf-vm/actions/setup@v4
      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@v4
        with:
          tool_versions: |
            action-validator 0.5.4
      - name: Lint Actions
        run: action-validator .github/workflows/*.yml
